- op: replace
  path: /spec/template/spec/containers/0/env/0
  value:
    name: LEADER_ELECT
    value: "false"
- op: replace
  path: /spec/template/spec/containers/0/env/2
  value:
    name: SERVER_CONFIG
    value: /etc/unikraft-provider/config.yaml
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: manager-config
      mountPath: /etc/unikraft-provider
      readOnly: true
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: manager-config
      configMap:
        name: manager-config
