# Test-infra overlay: Unikraft provider running in single-cell mode.
# Instance and Pod are co-located in the same cluster.
apiVersion: apiserver.config.datumapis.com/v1alpha1
kind: UnikraftProvider
metricsServer:
  bindAddress: ":8080"
  secureServing: false
downstreamResourceManagement:
locationClassName: "self-managed"
