apiVersion: v1
kind: ServiceAccount
metadata:
  name: ufo-apiserver
  namespace: datum-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ufo-controller
  namespace: datum-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ufo-activator
  namespace: datum-system
