apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWTRLSkc0cXc0RFl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qRXhNREU1TkRaYUZ3MHpOVEV4TVRreE1ESTBORFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURWNmVSaTBKU1dzQVBIVm94VVFwbHJZRWdsV1Y4dS9wbTZObUJKQ1d0cCtUdnNCdk40S1U0MmgyalkKVGdndGlRdkxpYkVQcVpEWmJRd3JoWThaN3huOUZYUmdBVG9UT3E4WGJoaXM5dFhEWlJXZkhuRDhyTzJVQnBneQpqTy9jOGVzNFhnS2xTbCt1NjMzdzMwa2wwemNISU1xbmo0Y1poQ1ZmeWFaVDdVQllsbGtZMmJ0b0dEZkU2QmpWCklQOW9hM0hYcGRwL0piSS81ek5ZSVZUWWJjdysxNVdXZ1c1UFlIRUV4aU9ZZ0RYakhEeGxNRzA4aWRWYTVWWVUKRzd0Y0NIWVdEVkZpc2VZdHV4TlI2SlFwZ3hZRUdEZk1WSkYxSUFEMW44YmJQU2s5Y0NOU1FaWmptL3VITUR3NApXK1ZNQWM4VGtrRnhUT00xS0hTQzRFdUZkQ2ZwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUZ1hoRFRQUmYyVUNEeHdqU2M3eGxLUXNuV1pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVArU1cxczZJYgpBVU40dHpjOWNSY3J1MGtuWkFTYjV6OUhWVGFGWlBvR1hUd1liU2h2aks1MjU5MWkvMHNsN1NOZ3UxMGlHRHlDCkVuandNbklISHRFQVl5Zk9QTExUSXJ6cmRMTDMwS0lLSW02SGViUy9qQ1B6T2tBQ2tJaWgydm84d3o0Ni9YVkkKMWRjaStwZ3MrcC95VzFGZnk4K1h3Y3dVTDJnVHltOWt6TTZHWXV6UDQ3a0VDWURWcS9hV3UzNHhCMDdPSUQyKwpSaTBSQXRSUjFNTjdrUE1SZnFaRWJRSC9hUmtMYkFkTXdWbVZGMzQ0NjMxK0EzT3FhTWxhdlZWaURReUJMVTdrCjZuS3hvUVFXYUhuSzFuT0hTSnRNaUNKTU9BcXlQU0lOT2Y3Wk96ZzFTK1BDVU1lR1BpRGs2VFpXbGtPZU9GdkcKMGRoRmpBVndTUm9uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://221148667505C393336C77FB0F4C0B92.sk1.us-west-1.eks.amazonaws.com
  name: arn:aws:eks:us-west-1:654654165949:cluster/my-cluster-tesing-openebs
- cluster:
    certificate-authority: /Users/petar/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 18 Feb 2026 11:21:26 CET
        provider: minikube.sigs.k8s.io
        version: v1.38.0
      name: cluster_info
    server: https://127.0.0.1:56373
  name: datum-edge
- cluster:
    certificate-authority: /Users/petar/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 18 Feb 2026 10:58:24 CET
        provider: minikube.sigs.k8s.io
        version: v1.38.0
      name: cluster_info
    server: https://127.0.0.1:54889
  name: datum-prime
- cluster:
    server: https://gke-aae886488ec047bca3a9d7ecf5d5301ff951-408500903801.us-central1.gke.goog
  name: gke_unikraft-playground_us-central1_demo-cluster
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRTkc2VjZIbWV4UlZSSkQ1blZSMlZPVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd1lUUmxNV1kxWXkxbU1EWXpMVFF3TXpRdFlUUTFPUzAwWVRGbE9EaGtNR1ExTkdRdwpJQmNOTWpZd01qRXlNVEV5TmpFeldoZ1BNakExTmpBeU1EVXhNakkyTVROYU1DOHhMVEFyQmdOVkJBTVRKREJoCk5HVXhaalZqTFdZd05qTXROREF6TkMxaE5EVTVMVFJoTVdVNE9HUXdaRFUwWkRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUx6aTlIeTZmdjFLOGxTL3BtQTJvSUducnJkZGErdjF0RmxLclVBdgpnVTZEU28rTlVyWEZtemRmUFd2L1JJWGFucEZoOEtjd09vcjVyQ1ExSHpyR2pyMlc3dUE4SStYcEhHUGhacWNXCkk2T0psUlNqMDNlZ3NFcWoyMkZ2SW9kcVllWklUMWdTM1NrcDVQa3piYnF1WlhlV1g3RE56VXMwUEVoanFBeVIKd0pUT1VyV2pQRzY0clZCczlsZ3BQOG9UWDVoWVU5Vkd0SEkvS2ZBVzZMdnJDS3BrZ3lMbnhDT09rdWxTYVU3cQpHUCtTYlUweGFSc2xpUGJvc2twV0hMN1lXNXVMMVV4TTF6VGJzOEg0c0wxVDNrTnVadUVlcUFVdlIyVE5VRlZ5CkUrN0FRMGJ3LzhtQytKTlM3QzJvemJKRXhROThqa1dHU3MzbTJ4clFMbFludUNHbmlvZnhGRnpaZTZ3ZkZaclkKRENZbmcxajdMRTJtNjgzdTJrZ1R5dWdHbXhkNjZteHVHM1lzcFhyWk9qMXhuZVlEVTFXcVlXTHVRa2JkcjU4dgpwOUQrODRaMEdFOGR2M0cvVHRSVFN6TXVLVUtJS0lycUc3UUpEaDVXYVVBRXVwZDBSdXpwUlM1dzMyeVpVbmFoCllQSVNkVnJmcmlXcXpoVGFsWG5OZHQ1ZDh3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVvNlB5S0wvSDAxSERwaFovcEZleUpqcC9ZUzR3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFHM2VzWEgwWVBDQ2RHajIrTUtKR2grQjh0SS9DYWdtNW1seWM2UUVpQ2RXClAzT3JZcGM4UjRIMWlobS84aTZrQzcvOHQxY0xDVFVNZk4yYkVLRXBycm5ubWdTQjFiWWpGajBPWDRqZCs0RE0KTG9JNWdHZWRLWndUcVMvUndvTWVkRUpJR1ppQ0ZTSWsrMmFuN2RDZ010WlJhSFNKd2hnYkVpL2x3anVNTTduYgpoS0dJbGViRmovTyszakRTNWlSY1N4NFJ5eEpEZ0xsZlU5SWlvSmdrWDBTOFA1MG03L0NDK0pCSGpaOHVoZWF0CnBkbnFVa3RlRGdjK2ZVQjlrazFHeVVMendlb1laQW1lWWNEN3l6enBNWXBSRXd6WlRUcE4zditYZXFJTm4xdG8KR0JJamFUNDJ4WWtOWjRER2EwZ1FMYktDU0xEcll5VC94a1YwMU5QUkxsTzlNNzRmbUE1Uy9MUTVFSVk2NE9YTwo0eFBNY29mV0hjTEg1MUFQaVRFbDVOUU5zMWRiWUVpeEVDZ2lFY25DV0lQeXUxTjNRTUczUDF5K2QrdW1VVmxGCjd5YWEyQkZyeVNoc3dTUHFoQ0JVSVIxMU1Xd3QxRGxZZkJSVmxtRWxSZFdhbkZQOFB5aitOdDk3bkQvd1pBZS8KZDFiWC9ZbFZMcnlyb3Faek5icG9CUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.222.85.38
  name: gke_unikraft-playground_us-central1_test-cluster
- cluster:
    certificate-authority: /Users/petar/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 26 Nov 2025 09:50:46 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://127.0.0.1:64641
  name: k8s-worker-node
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWTRLSkc0cXc0RFl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qRXhNREU1TkRaYUZ3MHpOVEV4TVRreE1ESTBORFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURWNmVSaTBKU1dzQVBIVm94VVFwbHJZRWdsV1Y4dS9wbTZObUJKQ1d0cCtUdnNCdk40S1U0MmgyalkKVGdndGlRdkxpYkVQcVpEWmJRd3JoWThaN3huOUZYUmdBVG9UT3E4WGJoaXM5dFhEWlJXZkhuRDhyTzJVQnBneQpqTy9jOGVzNFhnS2xTbCt1NjMzdzMwa2wwemNISU1xbmo0Y1poQ1ZmeWFaVDdVQllsbGtZMmJ0b0dEZkU2QmpWCklQOW9hM0hYcGRwL0piSS81ek5ZSVZUWWJjdysxNVdXZ1c1UFlIRUV4aU9ZZ0RYakhEeGxNRzA4aWRWYTVWWVUKRzd0Y0NIWVdEVkZpc2VZdHV4TlI2SlFwZ3hZRUdEZk1WSkYxSUFEMW44YmJQU2s5Y0NOU1FaWmptL3VITUR3NApXK1ZNQWM4VGtrRnhUT00xS0hTQzRFdUZkQ2ZwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUZ1hoRFRQUmYyVUNEeHdqU2M3eGxLUXNuV1pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVArU1cxczZJYgpBVU40dHpjOWNSY3J1MGtuWkFTYjV6OUhWVGFGWlBvR1hUd1liU2h2aks1MjU5MWkvMHNsN1NOZ3UxMGlHRHlDCkVuandNbklISHRFQVl5Zk9QTExUSXJ6cmRMTDMwS0lLSW02SGViUy9qQ1B6T2tBQ2tJaWgydm84d3o0Ni9YVkkKMWRjaStwZ3MrcC95VzFGZnk4K1h3Y3dVTDJnVHltOWt6TTZHWXV6UDQ3a0VDWURWcS9hV3UzNHhCMDdPSUQyKwpSaTBSQXRSUjFNTjdrUE1SZnFaRWJRSC9hUmtMYkFkTXdWbVZGMzQ0NjMxK0EzT3FhTWxhdlZWaURReUJMVTdrCjZuS3hvUVFXYUhuSzFuT0hTSnRNaUNKTU9BcXlQU0lOT2Y3Wk96ZzFTK1BDVU1lR1BpRGs2VFpXbGtPZU9GdkcKMGRoRmpBVndTUm9uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://221148667505C393336C77FB0F4C0B92.sk1.us-west-1.eks.amazonaws.com
  name: my-cluster-tesing-openebs.us-west-1.eksctl.io
- cluster:
    server: https://tailscale-operator
  name: tailscale-operator
- cluster:
    server: https://tailscale-operator-1.tail4243fd.ts.net
  name: tailscale-operator-1.tail4243fd.ts.net
- cluster:
    server: https://tailscale-operator-2.tail4243fd.ts.net
  name: tailscale-operator-2.tail4243fd.ts.net
- cluster:
    server: https://tailscale-operator.tail4243fd.ts.net
  name: tailscale-operator.tail4243fd.ts.net
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQitJOTR0YjJBc013RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1Ea3lNakkwTURoYUZ3MHpOVEV5TURjeU1qSTVNRGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURtQ2cwMzY4MUh5aWFVZVBPemMyZzFwVFhrcFRsMGlMQzBUT0JSanJHVWVsekRxNVQ3TG9JQ2JvSy8KVGhjc0IwUVF2TVdOeG5HbUhaOVlnV2s2bHBjSWhmT2JPNHRhcGtyOU01UzVIVndKemVzazJ3VnFWT0ZsR09maQpMMGlZU29pSmhQSkl0NlQrb25GNmZkK25ZT2FiQUdBcmJZZStnODFxam9ESTBYY0hMSGVmWXBMUUNjakRpSW9zCkFxWi9oZEFaa2pCbkhEU1U3OExlOFNBaTZMT0pYNFVVQ3FtSVQ1ZmMycjVTM3VqRlBUazN0cjZmejFyMG1YS1AKQ0tobk9RZmlobVZNWHg0djlrdUVuNlNRQkJmM2ErQUo1MmN1V1dMZk5vTDlaS0ZWZ2t3dUhCOEx1NXhlT2pyYgpXVktBc0ptNndoSDJlTFpHK21kWWplMDl5Tzh2QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaW8rcnhrYklnVW5LTlpRT005Zlc0b1Z1c1hqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZ3eDFPaFdFQwp1T1FwNUFLVThNaFVIcTNJbW1pWFkrbUZGVWNnQStSKzd6Tnd5Ym5rR0JyZFpNeXF1d0MwNGVKMnhNMHdvd3JOClBLYXFzOHQzbno0RmU0VmZHTnllMll0ZXQwWWNkMWRzenRibXdqbjhoOGNuaUthc0NqUGM2VXJsR0RBeDFaRHYKd1pqRDZMMERocFpuT2g3SktzY0FPcS9ac2JrUFRwcDY4TGRnYk8yU1V1RmRneTJPdHVmMzZpWmFDb3NhNmoyeQpXdXV6djhNb0NTMURQQkN3a3U3Qkp2czZpNTk5WmUzUDJQWTlKZXRXVW9HQW8yL1ZXQXRveXY1VWt6a0x1KzRvCnJMODl0S2xzQUcvZXBGSjhzVHVwQWhDbElZNWZ6OENSR20ybXE2MkpkOGhROEV2UGV5THpIWTljWXA2SXlmZGgKSS9Vc1l6UXd3RFYwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://207061BC5F5DDE0389DC923DD9B884BF.sk1.us-west-1.eks.amazonaws.com
  name: xata-demo.us-west-1.eksctl.io
contexts:
- context:
    cluster: arn:aws:eks:us-west-1:654654165949:cluster/my-cluster-tesing-openebs
    user: arn:aws:eks:us-west-1:654654165949:cluster/my-cluster-tesing-openebs
  name: arn:aws:eks:us-west-1:654654165949:cluster/my-cluster-tesing-openebs
- context:
    cluster: my-cluster-tesing-openebs.us-west-1.eksctl.io
    user: cli-local@my-cluster-tesing-openebs.us-west-1.eksctl.io
  name: cli-local@my-cluster-tesing-openebs.us-west-1.eksctl.io
- context:
    cluster: datum-edge
    extensions:
    - extension:
        last-update: Wed, 18 Feb 2026 11:21:26 CET
        provider: minikube.sigs.k8s.io
        version: v1.38.0
      name: context_info
    namespace: default
    user: datum-edge
  name: datum-edge
- context:
    cluster: datum-prime
    extensions:
    - extension:
        last-update: Wed, 18 Feb 2026 10:58:24 CET
        provider: minikube.sigs.k8s.io
        version: v1.38.0
      name: context_info
    namespace: default
    user: datum-prime
  name: datum-prime
- context:
    cluster: gke_unikraft-playground_us-central1_demo-cluster
    user: gke_unikraft-playground_us-central1_demo-cluster
  name: gke_unikraft-playground_us-central1_demo-cluster
- context:
    cluster: gke_unikraft-playground_us-central1_test-cluster
    user: gke_unikraft-playground_us-central1_test-cluster
  name: gke_unikraft-playground_us-central1_test-cluster
- context:
    cluster: k8s-worker-node
    extensions:
    - extension:
        last-update: Wed, 26 Nov 2025 09:50:46 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: k8s-worker-node
  name: k8s-worker-node
- context:
    cluster: xata-demo.us-west-1.eksctl.io
    user: petar@unikraft.io@xata-demo.us-west-1.eksctl.io
  name: petar@unikraft.io@xata-demo.us-west-1.eksctl.io
- context:
    cluster: tailscale-operator
    user: tailscale-auth
  name: tailscale-operator
- context:
    cluster: tailscale-operator-1.tail4243fd.ts.net
    user: tailscale-auth
  name: tailscale-operator-1.tail4243fd.ts.net
- context:
    cluster: tailscale-operator-2.tail4243fd.ts.net
    user: tailscale-auth
  name: tailscale-operator-2.tail4243fd.ts.net
- context:
    cluster: tailscale-operator.tail4243fd.ts.net
    user: tailscale-auth
  name: tailscale-operator.tail4243fd.ts.net
current-context: datum-prime
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-1:654654165949:cluster/my-cluster-tesing-openebs
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster-tesing-openebs
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: cli-local@my-cluster-tesing-openebs.us-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - my-cluster-tesing-openebs
      - --region
      - us-west-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: datum-edge
  user:
    client-certificate: /Users/petar/.minikube/profiles/datum-edge/client.crt
    client-key: /Users/petar/.minikube/profiles/datum-edge/client.key
- name: datum-prime
  user:
    client-certificate: /Users/petar/.minikube/profiles/datum-prime/client.crt
    client-key: /Users/petar/.minikube/profiles/datum-prime/client.key
- name: gke_unikraft-playground_us-central1_demo-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: /opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: gke_unikraft-playground_us-central1_test-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: /opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: k8s-worker-node
  user:
    client-certificate: /Users/petar/.minikube/profiles/k8s-worker-node/client.crt
    client-key: /Users/petar/.minikube/profiles/k8s-worker-node/client.key
- name: petar@unikraft.io@xata-demo.us-west-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - xata-demo
      - --region
      - us-west-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_PROFILE
        value: unikraft-power-user
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: tailscale-auth
  user:
    token: unused
