apiVersion: compute.datumapis.com/v1alpha
kind: Instance
metadata:
  name: example-sandbox-instance
  namespace: default
  annotations:
    cloud.unikraft.v1.services/domain: "my-subdomain"
    cloud.unikraft.v1.instances/scale_to_zero.policy: "on"
    cloud.unikraft.v1.instances/scale_to_zero.stateful: "true"
    cloud.unikraft.v1.instances/scale_to_zero.cooldown_time_ms: "1000"
spec:
  runtime:
    resources:
      instanceType: datumcloud/d1-standard-2 # unused in Unikraft provider
    sandbox:
      containers:
        - name: app
          image: datum/http-node26-test:latest
          env:
            - name: ENVIRONMENT
              value: production
          ports:
            - name: http
              port: 3000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
  networkInterfaces:
    - network:
        name: default
