apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations: # UKC specific annotations for scale to zero config
        cloud.unikraft.v1.instances/scale_to_zero.policy: "on"
        cloud.unikraft.v1.instances/scale_to_zero.stateful: "true"
        cloud.unikraft.v1.instances/scale_to_zero.cooldown_time_ms: "500"
      labels:
        app: my-app
    spec:
      tolerations: # Kraftlet comes with taints out of the box so other pods are not scheduled to it by default
        - key: "virtual-kubelet.io/provider"
          operator: "Equal"
          value: "ukc"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: kraftlet # selected by node name - could be scheduled based on UKC metro or other params
      containers:
        - name: bun
          image: datum/bun:latest
          command: ["/usr/bin/bun"]
          args:
            - run
            - /usr/src/server.ts
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          ports:
            - containerPort: 3000
