apiVersion: v1
kind: Service
metadata:
  name: my-app
  annotations:
    cloud.unikraft.v1.services/domain: my-app # UKC specific annotation for setting a specific subdomain
spec:
  selector:
    app: my-app
  ports:
    - port: 443
      name: http
      targetPort: 3000
      protocol: TCP
