apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: compute
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: compute
  path: overlays/single-cluster
