apiVersion: apiserver.config.datumapis.com/v1alpha1
kind: UnikraftProvider
metricsServer:
  bindAddress: ":8080"
  secureServing: false
webhookServer:
  port: 9443
downstreamResourceManagement:
locationClassName: "self-managed"
