//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&UnikraftProvider{}, func(obj interface{}) { SetObjectDefaults_UnikraftProvider(obj.(*UnikraftProvider)) })
	return nil
}

func SetObjectDefaults_UnikraftProvider(in *UnikraftProvider) {
	if in.MetricsServer.BindAddress == "" {
		in.MetricsServer.BindAddress = ":8080"
	}
	if in.WebhookServer.Port == 0 {
		in.WebhookServer.Port = 9443
	}
	if in.Discovery.Mode == "" {
		in.Discovery.Mode = "single"
	}
	if in.LocationClassName == "" {
		in.LocationClassName = "self-managed"
	}
}
