//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamResourceManagementConfig) DeepCopyInto(out *DownstreamResourceManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamResourceManagementConfig.
func (in *DownstreamResourceManagementConfig) DeepCopy() *DownstreamResourceManagementConfig {
	if in == nil {
		return nil
	}
	out := new(DownstreamResourceManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServerConfig) DeepCopyInto(out *MetricsServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServerConfig.
func (in *MetricsServerConfig) DeepCopy() *MetricsServerConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnikraftProvider) DeepCopyInto(out *UnikraftProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.MetricsServer = in.MetricsServer
	out.WebhookServer = in.WebhookServer
	out.DownstreamResourceManagement = in.DownstreamResourceManagement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnikraftProvider.
func (in *UnikraftProvider) DeepCopy() *UnikraftProvider {
	if in == nil {
		return nil
	}
	out := new(UnikraftProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnikraftProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookServerConfig) DeepCopyInto(out *WebhookServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookServerConfig.
func (in *WebhookServerConfig) DeepCopy() *WebhookServerConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookServerConfig)
	in.DeepCopyInto(out)
	return out
}
