apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ufo-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ufo-apiserver
subjects:
  - kind: ServiceAccount
    name: ufo-apiserver
    namespace: datum-system
---
# Allow ufo-apiserver to read the extension-apiserver-authentication configmap in kube-system
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ufo-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: ufo-apiserver
    namespace: datum-system
