apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - apiserver-clusterrole.yaml
  - apiserver-clusterrolebinding.yaml
  - activator-clusterrole.yaml
  - activator-clusterrolebinding.yaml
