# Lets kraftlet authorize requests to its kubelet API (kubectl exec, logs).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ukp-kraftlet-auth-delegator
  labels:
    app.kubernetes.io/name: kraftlet
    app.kubernetes.io/part-of: ukc
subjects:
  - kind: ServiceAccount
    name: kraftlet
    namespace: unikraft-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
